# Generated by Django 4.1.3 on 2023-08-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_products_order_order_items_orderitem_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at']},
        ),
    ]
